services:
  db:
    image: mariadb:11
    container_name: syci-auth-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: syci_auth
    ports:
      - "3306:3306"
    volumes:
      - syci_auth_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  syci_auth_db_data:
